apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: restful-distributed-lock-manager
    group: com.stakater.platform
    version: 0.5.3
    provider: stakater
  name: restful-distributed-lock-manager
spec:
  replicas: 1
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        app: restful-distributed-lock-manager
        group: com.stakater.platform
        version: 0.5.3
        provider: stakater
    spec:
      containers:
      - image: stakater/restful-distributed-lock-manager:0.5.3
        name: restful-distributed-lock-manager
        ports:
        - containerPort: 8888
          name: http
          protocol: TCP