apiVersion: v1
kind: Service
metadata:
  labels:
    app: restful-distributed-lock-manager
    group: com.stakater.platform
    version: 0.5.3
    provider: stakater
  name: restful-distributed-lock-manager
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8888
  selector:
    app: restful-distributed-lock-manager
    group: com.stakater.platform
    provider: stakater